### ISSUE TITLE
Scroll bar is not transparent

### ISSUE THREAD

**Issue by Doesntmeananything** [barklan/kanagawa.vscode#13]
Hi!

I've noticed that the scroll bar is not transparent and can hide various code markers (for selection, warnings, errors, etc.). Here's the comparison with the default theme:

Transparent scroll bar
![image](https://user-images.githubusercontent.com/34657799/175785498-d8dbce22-65b4-4ae6-b7cc-ec6e09ccec87.png)

Non-transparent scroll bar
![image](https://user-images.githubusercontent.com/34657799/175785512-0a57051d-71ef-4e3d-bb62-749bf041e05f.png)

You can see that the Kanagawa theme hides the markers and makes it a bit more difficult to navigate around. Do you think transparency can be added here?

Thanks!

**Comment by barklan** [comment]
Thanks for reporting! Added transparency in v1.5.1. I tried to make it about same contrast level as in the default theme.
